### ISSUE TITLE
Sometimes, Take Off command is ignored

### ISSUE THREAD

**Issue by poshaughnessy** [poshaughnessy/web-bluetooth-parrot-drone#2]
Every now and again, the drone just ignores the Take Off command and doesn't do anything. I'm not sure of a pattern or cause yet...

**Comment by poshaughnessy** [comment]
Could be a browser issue: closing the Chrome for Android Dev app and re-opening it appears to fix it.

**Comment by jyasskin** [comment]
For Chrome browser issues, see http://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs for how to collect enough information for us to debug.

**Comment by poshaughnessy** [comment]
Should be resolved by https://github.com/poshaughnessy/web-bluetooth-parrot-drone/pull/11.
