### ISSUE TITLE
Origin Trial is not working?

### ISSUE THREAD

**Issue by poshaughnessy** [poshaughnessy/web-bluetooth-parrot-drone#8]
Just got around to switching off the Web Bluetooth feature flag and seeing if it worked at https://webdr.one without it. However, pressing Connect does nothing - it does not come up with a scan/pairing prompt.

@beaufortfrancois please might you know where I'm going wrong?

**Comment by beaufortfrancois** [comment]
Origin Trial token only works with Chrome M53 onwards. Since Chrome Stable is still M52 (for still a week at least), you may want to use Chrome Beta on Desktop and Android.

Does that work better?

**Comment by poshaughnessy** [comment]
Oops yeah I just spotted the answer on caniuse.com :D Thanks, yes that works!
